### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by phenomen** [rraallvv/Layer2SpriteSheet#1]
I get this error when trying to launch script: 

Error 48: File or directory doesn't exist. 
Line: 66
-> #Include "include/json2.js"

![upn6nqr](https://cloud.githubusercontent.com/assets/138311/24745788/ff3d8e5a-1ac7-11e7-9cf8-369e57af8593.png)

**Comment by rraallvv** [comment]
@Phenomen what version of Photoshop is that one?

**Comment by phenomen** [comment]
@rraallvv latest (Photoshop CC  2017.0.1)

**Comment by rraallvv** [comment]
@Phenomen did you copy the entire folder Layer2SpriteSheet with its content?

The path would end up being something like `C:\Program Files\Adobe\Adobe Photoshop CC 2017\Presets\Scripts\Layer2SpriteSheet`

Please check that the **include** folder and its contents is in `C:\Program Files\Adobe\Adobe Photoshop CC 2017\Presets\Scripts\Layer2SpriteSheet\include`

I think that is the easiest way to install it.

**Comment by phenomen** [comment]
Ah, I'm sorry. Usually it's enough to copy .jsx for scripts. Issue fixed, thanks!
